/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PastOrdersLazyImport = createFileRoute('/past-orders')()
const OrderLazyImport = createFileRoute('/order')()
const ContactUsLazyImport = createFileRoute('/contact-us')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PastOrdersLazyRoute = PastOrdersLazyImport.update({
  path: '/past-orders',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/past-orders.lazy').then((d) => d.Route))

const OrderLazyRoute = OrderLazyImport.update({
  path: '/order',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order.lazy').then((d) => d.Route))

const ContactUsLazyRoute = ContactUsLazyImport.update({
  path: '/contact-us',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact-us.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsLazyImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderLazyImport
      parentRoute: typeof rootRoute
    }
    '/past-orders': {
      id: '/past-orders'
      path: '/past-orders'
      fullPath: '/past-orders'
      preLoaderRoute: typeof PastOrdersLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/order': typeof OrderLazyRoute
  '/past-orders': typeof PastOrdersLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/order': typeof OrderLazyRoute
  '/past-orders': typeof PastOrdersLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/order': typeof OrderLazyRoute
  '/past-orders': typeof PastOrdersLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact-us' | '/order' | '/past-orders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact-us' | '/order' | '/past-orders'
  id: '__root__' | '/' | '/contact-us' | '/order' | '/past-orders'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactUsLazyRoute: typeof ContactUsLazyRoute
  OrderLazyRoute: typeof OrderLazyRoute
  PastOrdersLazyRoute: typeof PastOrdersLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactUsLazyRoute: ContactUsLazyRoute,
  OrderLazyRoute: OrderLazyRoute,
  PastOrdersLazyRoute: PastOrdersLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/contact-us",
        "/order",
        "/past-orders"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/contact-us": {
      "filePath": "contact-us.lazy.jsx"
    },
    "/order": {
      "filePath": "order.lazy.jsx"
    },
    "/past-orders": {
      "filePath": "past-orders.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
